spring:
  autoconfigure:
    exclude:
      - "org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration"
      - "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - enabled: false
      active-directory:
        enabled: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      base-url: ${ANTHROPIC_BASE_URL}
    elevenlabs:
      base-url: ${ELEVEN_LABS_BASE_URL}
      api-key: ${ELEVEN_LABS_API_KEY}
google:
  ai:
    apiKey: ${GOOGLE_AI_API_KEY}
    baseUrl: ${GOOGLE_AI_BASE_URL}
