dictionary-api-token: test-token
rate-limit:
  image-per-minute:
  audio-per-minute:
spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - enabled: false
      active-directory:
        enabled: false
  ai:
    openai-sdk:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      base-url: ${ANTHROPIC_BASE_URL}
    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        base-url: ${GOOGLE_AI_BASE_URL}
    elevenlabs:
      base-url: ${ELEVEN_LABS_BASE_URL}
      api-key: ${ELEVEN_LABS_API_KEY}
