spring:
  autoconfigure:
    exclude:
      - "org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration"
      - "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"
  cloud:
    azure:
      active-directory:
        enabled: false
langsmith:
  enabled: false
openai:
  apiKey: ${OPENAI_API_KEY}
  baseUrl: ${OPENAI_BASE_URL}
google:
  ai:
    apiKey: ${GOOGLE_AI_API_KEY}
    baseUrl: ${GOOGLE_AI_BASE_URL}
elevenlabs:
  apiKey: ${ELEVEN_LABS_API_KEY}
  baseUrl: ${ELEVEN_LABS_BASE_URL}
