storage:
  directory: ./storage
spring:
  docker:
    compose:
      enabled: true
      file: ./compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/learnlanguage
    username: postgres
    password: postgres
  cloud:
    azure:
      active-directory:
        credential:
          client-secret: ${api-client-secret}
management:
  server:
    port: 8182
